name       : perl-class-accessor
version    : '0.51'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/K/KA/KASEI/Class-Accessor-0.51.tar.gz : bf12a3e5de5a2c6e8a447b364f4f5a050bf74624c56e315022ae7992ff2f411c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module automagically generates accessors/mutators for your class.
description: |
    This module automagically generates accessors/mutators for your class.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
