name       : perl-class-accessor
version    : 0.34
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/K/KA/KASEI/Class-Accessor-0.34.tar.gz : cdb1e0cdf8380fb9b63b44c33ce5afc1068736d55ac5904bf0eaa1efc1c3cefc
license    : GPL-1.0
component  : programming.perl
summary    : This module automagically generates accessors/mutators for your class.
description: |
    This module automagically generates accessors/mutators for your class.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
